import { Header } from "@/components/Header";
import "./globals.css";
import { MessageProvider } from "@/contexts/appContext";

export const metadata = {
  title: "MotivatorAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MessageProvider>
      <body>
        <Header />
        {children}
      </body>
      </MessageProvider>
    </html>
  );
}
